import { Inter, Metrophobic } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/header/Header";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const metrophobic = Metrophobic({
  variable: "--font-metrophobic",
  subsets: ["latin"],
  weight: ["400"],
});

export const grotesk = localFont({
  src: [
    {
      path: "../../public/fonts/ClashGrotesk/ClashGrotesk-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/ClashGrotesk/ClashGrotesk-Semibold.otf",
      weight: "600",
      style: "normal",
    },
  ],
  variable: "--font-grotesk",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${metrophobic.variable} ${grotesk.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
